services:
  - type: web
    name: da-chen-guang
    env: java
    buildCommand: "mvn clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    plan: free